Домашнее задание №5
ovsyannikovas/2022-2-VK-EDU-FS-Frontend-S-Ovsyannikova pull request #5
Opened 2022-11-17 18:31 UTC by ovsyannikovas

# Домашнее задание №5

Прошу @martinkomitsky или @haseprogam проверить его.

Что было сделано:
* Переписано на компоненты react
* Стили пока находятся в одном файле

2022-11-19 20:34 UTC, martinkomitsky commented on react-chat/webpack.config.js
> +const path = require('path');
этот файл не нужен для сборки

2022-11-19 20:35 UTC, martinkomitsky commented on react-chat/src/components/Message/Message.jsx
> +                    <i className="material-icons">{check}</i>
заменить подключение иконок на пакет (ссылка в условии ДЗ)

2022-11-19 20:35 UTC, martinkomitsky requested changes
нужно пару фиксов

2022-11-19 21:34 UTC, ovsyannikovas commented
Исправлено

2022-11-20 10:46 UTC, martinkomitsky approved these changes
супер, 10

2022-11-20 10:46 UTC, merged